/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CruiseDeal = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'departurePort' : IDL.Text,
  'shipName' : IDL.Text,
  'durationNights' : IDL.Nat,
  'pricePerPerson' : IDL.Float64,
  'highlights' : IDL.Vec(IDL.Text),
  'discountPct' : IDL.Nat,
  'currency' : IDL.Text,
  'rating' : IDL.Float64,
  'cruiseLine' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Carrier = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Destination = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarriers' : IDL.Func([], [IDL.Vec(Carrier)], ['query']),
  'getDeal' : IDL.Func([IDL.Text], [IDL.Opt(CruiseDeal)], ['query']),
  'getDealsByCarrier' : IDL.Func([IDL.Text], [IDL.Vec(CruiseDeal)], ['query']),
  'getDealsByDestination' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CruiseDeal)],
      ['query'],
    ),
  'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getSavedDeals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSavedDeal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDeal' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CruiseDeal = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'departurePort' : IDL.Text,
    'shipName' : IDL.Text,
    'durationNights' : IDL.Nat,
    'pricePerPerson' : IDL.Float64,
    'highlights' : IDL.Vec(IDL.Text),
    'discountPct' : IDL.Nat,
    'currency' : IDL.Text,
    'rating' : IDL.Float64,
    'cruiseLine' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Carrier = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Destination = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarriers' : IDL.Func([], [IDL.Vec(Carrier)], ['query']),
    'getDeal' : IDL.Func([IDL.Text], [IDL.Opt(CruiseDeal)], ['query']),
    'getDealsByCarrier' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CruiseDeal)],
        ['query'],
      ),
    'getDealsByDestination' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CruiseDeal)],
        ['query'],
      ),
    'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getSavedDeals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSavedDeal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDeal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };